@echo off
title DARK EMPIRE DESKTOP APP
echo [System] Starting Dark Empire Desktop Application...
echo [System] Installing dependencies if needed...
call npm install
echo [System] Launching App...
npm run app
pause
